### ISSUE TITLE
Howto refresh auth token?

### ISSUE THREAD

**Issue by andig** [Tobiaswk/dartnissanconnect#1]
I'm wondering how to use the refresh toking for getting a new access token in long-running applications? Which endpoint to use?

**Comment by andig** [comment]
Found it: refreshing works like this:

	uri := fmt.Sprintf("%s/oauth2/%s/access_token", nissanAuthBaseURL, nissanRealm)

	data := url.Values{
		"client_id":     []string{nissanClientID},
		"client_secret": []string{nissanClientSecret},
		"grant_type":    {"refresh_token"},
		"refresh_token": {v.tokens.RefreshToken},
	}

	uri += "?" + data.Encode()
	req, err := request.New(http.MethodPost, uri, nil, request.URLEncoding)
	if err == nil {
		var tokens oidc.Tokens
		if err = v.DoJSON(req, &tokens); err == nil && v.tokens.AccessToken == "" {
			err = errors.New("missing access token")
		}
		fmt.Println(tokens)
	}

**Comment by Tobiaswk** [comment]
@andig Great stuff! Thank you so much for the update!
