### ISSUE TITLE
Unauthorized, detail: Invalid or missing token

### ISSUE THREAD

**Issue by pjpeartree** [Tobiaswk/dartnissanconnect#5]
Hi Tobias,

Thank you for may this available. I am using your library to automate my EVSE to support changing modes (Weekly Range, City Range, Long Range and Solar Only).

Since  28-03-2022 18:40 I am receiving the following error:

`$ Invoking NissanConnect/Kamereon API: https://alliance-platform-usersadapter-prod.apps.eu.kamereon.io/user-adapter/v1/users/current
$ Params: null
$ Headers: {Authorization: Bearer Bdu6XFRP3mIjlEdID-4jbrb-PK0}
$ Result: {userId: 822044}
$ Invoking NissanConnect/Kamereon API: https://nci-bff-web-prod.apps.eu.kamereon.io/bff-web/v4/users/822044/cars
$ Params: null
$ Headers: {Authorization: Bearer Bdu6XFRP3mIjlEdID-4jbrb-PK0}
$ Result: {errors: {status: Unauthorized, code: 401000, title: Unauthorized, detail: Invalid or missing token, meta: [{spanId: 3179672e252f81c4, traceId: 98ef414785b8d28d, parentSpanId: e4355c6638571dfb, component: alliance-platform-usersadapter-prod}]}}`

Is this related to the NissanConnect App update? Is there a new API from Nissan?
Sow your commit on lib/src/nissanconnect_session.dart but it looks like is just a comment update.

Please, let me know if you need help or additional information to test fixes.

Regards,
Pedro

**Comment by pirracas77** [comment]
Same here!

**Comment by Tobiaswk** [comment]
Hello Pedro,

Yes I have fixed it. There are multiple commits but it is working again. Just use the latest on master branch.

Den 30. marts 2022 12.20.03 CEST, pjpeartree ***@***.***> skrev:

**Comment by Tobiaswk** [comment]
Just to explain; Nissan made changes to their API. New endpoints and client secret.

Like I said it is fixed ;)

Den 30. marts 2022 12.42.27 CEST, Tobias Westergaard Kjeldsen ***@***.***> skrev:

**Comment by Tobiaswk** [comment]
I'm going to close this.

**Comment by pjpeartree** [comment]
I do confirm that is working now. My bad,  just took a look at the last commit changes. 
After changing the secret and endpoints, it works faultlessly.
Thank you
